# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d78f12f25041bd467aebe26646e0d84d1df046de452cb7167779bd322881cfe72be3c475318f357d6812fba468a8737927e6d7ab4b9a3a182988b78ec81a9e65

test:
  secret_key_base: 256a13a04eac6c45783499d862053ea8039b6c5964b2f49ff821cbf501bb377eb9854b6a2e953e62f474835d538b6cc302841f4c90e7c75f791c9b4d3312b571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
